# {{title}}

**Date:** {{date}}
**Tags:** {{tags}}

## Questions

{{questions}}

## Key Findings

{{findings}}

## Sources

{{sources}}

## Next Steps

{{next_steps}}

---
*Research template — auto-generated by Hermes shared memory layer*
